# Generated by Django 4.0.4 on 2022-06-02 16:18

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('summary', models.TextField(blank=True, help_text='Įveskite trumpą knygos aprašymą', max_length=1000)),
                ('isbn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('biografija', 'Biografija'), ('gamta', 'Gamta'), ('grozine literatura', 'Grožinė literatūra'), ('humoras ir pramogos', 'Humoras & Pramogos'), ('inzinerija ir transportas', 'Inžinerija & Transportas'), ('istorija', 'Istorija'), ('keliones', 'Kelionės'), ('komiksai', 'Komiksai'), ('kompiuteriai ir it technologijos', 'Kompiuteriai ir IT technologijos'), ('kulinarija', 'Kulinarija'), ('medicina', 'Medicina'), ('menas', 'Menas'), ('mokslas', 'Mokslas'), ('moksline fantastika', 'Mokslinė fantastika'), ('politika ir socialiniai mokslai', 'Politika ir socialiniai mokslai'), ('pomegiai', 'Pomėgiai'), ('religija', 'Religija'), ('sportas ir aktyvus poilsis', 'Sportas ir aktyvus poilsis'), ('sveikata ir dieta', 'Sveikata ir dieta'), ('seima', 'Šeima'), ('teise', 'Teisė'), ('vaikams ir jaunimui', 'Vaikams ir jaunimui'), ('verslas', 'Verslas'), ('NOT_INCLUDED', 'Kita')], max_length=255)),
                ('upload', models.ImageField(blank=True, default='no_book_image.png', max_length=150, null=True, upload_to=books.models.upload_to)),
                ('language', models.CharField(choices=[('LT', 'Lietuvių'), ('EN', 'Anglų'), ('PL', 'Lenkų'), ('RU', 'Rusų'), ('XX', 'Kita')], default='LT', max_length=150)),
                ('for_sale', models.BooleanField(help_text='Pardavimas')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('for_exchange', models.BooleanField(help_text='Apsikeitimas')),
                ('for_donation', models.BooleanField(help_text='Dovana')),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=10000)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_username', models.CharField(max_length=100)),
                ('comment_name', models.CharField(help_text='Komentaro pavadinimas', max_length=50)),
                ('comment_text', models.TextField(help_text='Komentaro tekstas', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commented_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
