# Generated by Django 4.0.4 on 2022-06-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Įveskite trumpą knygos aprašymą'),
        ),
    ]
